"use client";

import { ChangeEvent, useMemo, useState } from "react";

type Service = "Express" | "Visita profesional";
type Answers = { service:Service; purpose:string; propertyType:string; address:string; commune:string; area:string; name:string; email:string; phone:string };
type FileState = { kind:string; name:string; size:number };
const initial:Answers={service:"Express",purpose:"",propertyType:"",address:"",commune:"",area:"",name:"",email:"",phone:""};
const documentTypes=[
  {kind:"propiedad",title:"Identificación de la propiedad",help:"Escritura, avalúo fiscal o contribuciones",accept:".pdf,.jpg,.jpeg,.png"},
  {kind:"superficie",title:"Superficie y distribución",help:"Plano, croquis o certificado municipal",accept:".pdf,.jpg,.jpeg,.png"},
  {kind:"fotos",title:"Fotografías del inmueble",help:"Interior, exterior y vista del entorno",accept:".jpg,.jpeg,.png,.heic"},
];

export default function Home(){
  const [stage,setStage]=useState(-1),[answers,setAnswers]=useState<Answers>(initial),[files,setFiles]=useState<FileState[]>([]),[notice,setNotice]=useState(""),[paid,setPaid]=useState(false);
  const completion=Math.round((files.length/documentTypes.length)*100);
  const folio=useMemo(()=>`TG-${new Date().getFullYear().toString().slice(-2)}-${2187+answers.address.length*7}`,[answers.address]);
  function begin(service:Service="Express"){setAnswers(current=>({...current,service}));setStage(0);window.scrollTo({top:0,behavior:"smooth"})}
  function go(next:number){setNotice("");setStage(next);window.scrollTo({top:0,behavior:"smooth"})}
  function upload(kind:string,event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;setFiles(current=>[...current.filter(item=>item.kind!==kind),{kind,name:file.name,size:file.size}]);setNotice("Antecedente recibido correctamente");event.target.value=""}
  function pay(){setPaid(true);window.localStorage.setItem("tasago_v5_request",JSON.stringify({folio,answers,files,status:"En validación"}));go(9)}
  if(stage===-1)return <Landing onStart={begin}/>;
  return <main className="app-shell">
    <header className="app-header"><button className="brand-button" onClick={()=>setStage(-1)} aria-label="Volver al inicio"><img src="/tasago-logo-final.png" alt="TasaGo"/></button><div className="secure-label"><span>✓</span> Proceso privado y seguro</div></header>
    <MacroProgress stage={stage}/><section className="conversation">
      {stage===0&&<ChoiceScreen eyebrow="Empecemos" title="¿Qué tipo de tasación necesitas?" text="Puedes cambiarla antes de pagar." options={[{value:"Express",title:"Tasación Express",detail:"100% digital · desde 24 h hábiles",badge:"$39.990"},{value:"Visita profesional",title:"Tasación con visita",detail:"Inspección presencial y análisis especializado",badge:"Desde 1,5 UF"}]} selected={answers.service} onSelect={value=>{setAnswers({...answers,service:value as Service});go(1)}}/>}
      {stage===1&&<ChoiceScreen eyebrow="Tu decisión" title="¿Para qué necesitas la tasación?" text="Esto nos ayuda a enfocar correctamente el informe." options={[{value:"Vender",title:"Quiero vender",detail:"Definir un precio respaldado"},{value:"Comprar",title:"Quiero comprar",detail:"Validar antes de decidir"},{value:"Crédito",title:"Crédito o garantía",detail:"Presentar un valor técnico"},{value:"Legal",title:"Herencia o trámite legal",detail:"Contar con respaldo profesional"}]} selected={answers.purpose} onSelect={value=>{setAnswers({...answers,purpose:value});go(2)}}/>}
      {stage===2&&<ChoiceScreen eyebrow="La propiedad" title="¿Qué tipo de inmueble es?" text="Selecciona la opción que mejor lo describe." options={[{value:"Departamento",title:"Departamento",detail:"Unidad en edificio o condominio"},{value:"Casa",title:"Casa",detail:"Aislada, pareada o en condominio"},{value:"Terreno",title:"Terreno",detail:"Urbano o rural"},{value:"Oficina o local",title:"Oficina o local",detail:"Uso comercial o profesional"}]} selected={answers.propertyType} onSelect={value=>{setAnswers({...answers,propertyType:value});go(3)}}/>}
      {stage===3&&<QuestionScreen eyebrow="Ubicación" title="¿Dónde está la propiedad?" text="Usaremos la dirección para analizar su entorno y mercado."><label className="input-group"><span>Dirección</span><input autoFocus value={answers.address} onChange={e=>setAnswers({...answers,address:e.target.value})} placeholder="Ej. Av. Irarrázaval 3456"/></label><label className="input-group"><span>Comuna</span><select value={answers.commune} onChange={e=>setAnswers({...answers,commune:e.target.value})}><option value="">Selecciona una comuna</option>{["Santiago","Providencia","Ñuñoa","Las Condes","Vitacura","La Reina","Peñalolén","La Florida","San Miguel","Maipú","Colina","Otra comuna RM"].map(x=><option key={x}>{x}</option>)}</select></label><Primary disabled={!answers.address||!answers.commune} onClick={()=>go(4)}>Continuar</Primary></QuestionScreen>}
      {stage===4&&<QuestionScreen eyebrow="Características" title="¿Cuál es la superficie aproximada?" text="No importa si no tienes la cifra exacta. Luego la validaremos con tus antecedentes."><label className="input-group area-input"><span>Superficie total</span><div><input autoFocus inputMode="numeric" value={answers.area} onChange={e=>setAnswers({...answers,area:e.target.value.replace(/\D/g,"")})} placeholder="80"/><b>m²</b></div></label><Primary disabled={!answers.area} onClick={()=>go(5)}>Continuar</Primary></QuestionScreen>}
      {stage===5&&<QuestionScreen eyebrow="Tu información" title="¿Dónde te enviamos el resultado?" text="También podrás seguir el proceso con un folio privado."><label className="input-group"><span>Nombre completo</span><input value={answers.name} onChange={e=>setAnswers({...answers,name:e.target.value})} placeholder="Tu nombre"/></label><label className="input-group"><span>Correo electrónico</span><input type="email" value={answers.email} onChange={e=>setAnswers({...answers,email:e.target.value})} placeholder="nombre@correo.cl"/></label><label className="input-group"><span>Teléfono</span><input type="tel" value={answers.phone} onChange={e=>setAnswers({...answers,phone:e.target.value})} placeholder="+56 9 1234 5678"/></label><Primary disabled={!answers.name||!answers.email||!answers.phone} onClick={()=>go(6)}>Crear expediente seguro</Primary><p className="privacy-note">Tus datos se usan únicamente para gestionar esta solicitud.</p></QuestionScreen>}
      {stage===6&&<UploadScreen files={files} completion={completion} onUpload={upload} onRemove={kind=>setFiles(current=>current.filter(item=>item.kind!==kind))} onContinue={()=>go(7)}/>} {stage===7&&<Summary answers={answers} files={files} completion={completion} folio={folio} onEdit={go} onContinue={()=>go(8)}/>} {stage===8&&<Checkout answers={answers} completion={completion} folio={folio} onPay={pay}/>} {stage===9&&<Status paid={paid} answers={answers} folio={folio} completion={completion} onNew={()=>{setAnswers(initial);setFiles([]);setPaid(false);setStage(-1)}}/>}
    </section>{stage>0&&stage<9&&<button className="back-link" onClick={()=>go(stage-1)}>← Volver</button>}{notice&&<div className="toast" role="status"><span>✓</span>{notice}</div>}
  </main>
}

function Landing({onStart}:{onStart:(service?:Service)=>void}){return <main className="site-shell">
  <nav className="site-nav"><img src="/tasago-logo-final.png" alt="TasaGo Inteligencia Territorial"/><div><a href="#servicios">Servicios</a><a href="#como-funciona">Cómo funciona</a><a href="#geo">TasaGo Geo</a><a href="/panel">Seguimiento</a></div></nav>
  <section className="hero"><div className="hero-content"><span className="hero-kicker"><i>✓</i> Tasaciones inmobiliarias en Chile</span><h1>Tranquilidad para<br/><em>decidir bien.</em></h1><p>No vendemos una cifra. Te entregamos seguridad profesional para vender, comprar o respaldar una decisión importante.</p><button onClick={()=>onStart("Express")}>Comenzar Tasación <span>→</span></button><small>Te tomará menos de 5 minutos comenzar</small></div><div className="hero-assurance"><div className="expert-avatar">JC</div><div><strong>Revisión profesional TasaGo</strong><span>Experiencia, metodología y trazabilidad</span></div><b>✓</b></div></section>
  <section className="trust-section"><header><span>Confianza desde el primer momento</span><h2>Tu propiedad merece criterio, no una estimación improvisada.</h2></header><div className="trust-grid">{[["PERITO","Perito tasador","Criterio profesional aplicado a cada decisión."],["24+","Años de experiencia","Conocimiento real del mercado inmobiliario."],["MÉTODO","Análisis de mercado","Comparables, microzona y variables verificables."],["PDF","Informe profesional","Folio, metodología, respaldo y firma simple."],["1:1","Atención personalizada","Acompañamiento claro cuando lo necesites."]].map(([icon,title,text])=><article key={title}><span>{icon}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="process-section" id="como-funciona"><header><span>Simple y acompañado</span><h2>De tu propiedad a una decisión segura.</h2><p>La aplicación te guía. Siempre sabrás qué viene y cuánto falta.</p></header><div className="process-line">{[["1","Cuéntanos","Responde preguntas simples, una a la vez."],["2","Sube antecedentes","Te mostramos exactamente qué necesitamos."],["3","Analizamos","Validamos documentos y mercado comparable."],["4","Recibe tu informe","Descarga tu PDF y decide con respaldo."]].map(([n,t,d],index)=><article key={n}><div><span>{n}</span>{index<3&&<i/>}</div><h3>{t}</h3><p>{d}</p></article>)}</div></section>
  <section className="services-section" id="servicios"><header><span>Elige según tu necesidad</span><h2>Dos maneras de sentirte seguro.</h2></header><div className="service-grid"><article className="service-card featured"><span className="service-badge">MÁS ELEGIDA</span><div className="service-icon">24h</div><h3>Tasación Express</h3><p className="service-lead">100% digital, rápida y trazable.</p><ul><li>Validación de antecedentes</li><li>Análisis de mercado y comparables</li><li>Rango de valor comercial</li><li>Informe PDF con folio</li></ul><div className="service-price"><strong>$39.990</strong><span>pago único</span></div><button onClick={()=>onStart("Express")}>Comenzar Express</button><small>Entrega desde 24 h hábiles*</small></article><article className="service-card"><span className="service-badge subtle">MÁXIMO RESPALDO</span><div className="service-icon dark">VISITA</div><h3>Tasación con visita profesional</h3><p className="service-lead">Inspección presencial y criterio especializado.</p><ul><li>Visita coordinada al inmueble</li><li>Levantamiento y registro fotográfico</li><li>Comparables ajustados por tasador</li><li>Informe técnico con firma simple</li></ul><div className="service-price"><strong>Desde 1,5 UF</strong><span>según propiedad</span></div><button className="outline" onClick={()=>onStart("Visita profesional")}>Solicitar visita</button><small>Agenda confirmada personalmente</small></article></div></section>
  <section className="geo-section" id="geo"><div className="geo-copy"><span>TASAGO GEO · INTELIGENCIA TERRITORIAL</span><h2>El valor no está sólo dentro de la propiedad.</h2><p>TasaGo Geo incorpora la ubicación, microzona, conectividad, equipamiento y comportamiento del mercado para entender qué ocurre alrededor del inmueble y cómo influye en su valor.</p><div className="geo-features"><div><b>01</b><span><strong>Microzona real</strong><small>Análisis del entorno inmediato, no sólo de la comuna.</small></span></div><div><b>02</b><span><strong>Comparables georreferenciados</strong><small>Referencias cercanas, visibles y trazables.</small></span></div><div><b>03</b><span><strong>Lectura territorial</strong><small>Servicios, accesos y variables urbanas relevantes.</small></span></div></div></div><aside className="geo-map" aria-label="Ejemplo de análisis territorial TasaGo Geo"><header><img src="/tasago-logo-final.png" alt="TasaGo"/><b>GEO</b><span>ÑUÑOA · SANTIAGO</span></header><div className="map-surface"><i className="road r1"/><i className="road r2"/><i className="road r3"/><span className="pin p1">UF 63</span><span className="pin p2">UF 66</span><span className="pin p3">UF 61</span><span className="pin subject">PROPIEDAD</span><div className="radius"/></div><footer><span><i/> Comparable</span><span><i/> Propiedad analizada</span></footer></aside></section>
  <section className="proof-band"><div><span>24+</span><p>años respaldando decisiones inmobiliarias</p></div><blockquote>“La tecnología simplifica el proceso. La experiencia le da sentido al resultado.”</blockquote></section>
  <section className="report-section"><div><span>Un resultado que puedes presentar</span><h2>Claro para entender.<br/>Profesional para respaldar.</h2><p>Cada informe reúne identificación, antecedentes, análisis del sector, comparables, metodología, valor estimado, folio y firma simple.</p><a href="/ejemplo-informe-express.pdf" target="_blank">Ver informe de ejemplo <b>PDF ↗</b></a></div><aside><div className="report-paper"><header><img src="/tasago-logo-final.png" alt="TasaGo"/><span>INFORME DE TASACIÓN</span></header><div className="report-photo"/><h3>Valor comercial estimado</h3><strong>UF 4.850 — UF 5.550</strong><div className="report-lines"><i/><i/><i/><i/></div><footer>Folio TG-2608-0147 · Firma simple</footer></div></aside></section>
  <section className="final-banner"><span>Tu próxima decisión puede empezar con más tranquilidad.</span><h2>Conoce el valor de tu propiedad con respaldo profesional.</h2><button onClick={()=>onStart("Express")}>Comenzar Tasación <b>→</b></button></section>
  <footer className="site-footer"><img src="/tasago-logo-final.png" alt="TasaGo"/><p>Inteligencia territorial para decisiones importantes.</p><span>© {new Date().getFullYear()} TasaGo · Santiago, Chile</span></footer>
</main>}

function MacroProgress({stage}:{stage:number}){const current=stage<=5?1:stage===6?2:stage<=8?3:4;return <section className="macro-progress"><div className="progress-copy"><span>Paso {current} de 4</span><b>{["Cuéntanos","Antecedentes","Confirmación","Resultado"][current-1]}</b></div><div className="progress-line">{[1,2,3,4].map(n=><span key={n} className={n<=current?"active":""}><i>{n<current?"✓":n}</i></span>)}</div></section>}
function QuestionScreen({eyebrow,title,text,children}:{eyebrow:string;title:string;text:string;children:React.ReactNode}){return <div className="question-screen"><header><span>{eyebrow}</span><h1>{title}</h1><p>{text}</p></header><div className="answer-area">{children}</div></div>}
function ChoiceScreen({eyebrow,title,text,options,selected,onSelect}:{eyebrow:string;title:string;text:string;options:{value:string;title:string;detail:string;badge?:string}[];selected:string;onSelect:(value:string)=>void}){return <QuestionScreen eyebrow={eyebrow} title={title} text={text}><div className="choice-grid">{options.map(option=><button key={option.value} className={selected===option.value?"selected":""} onClick={()=>onSelect(option.value)}><span className="choice-check">{selected===option.value?"✓":"→"}</span><div><strong>{option.title}</strong><small>{option.detail}</small></div>{option.badge&&<b>{option.badge}</b>}</button>)}</div></QuestionScreen>}
function Primary({children,disabled,onClick}:{children:React.ReactNode;disabled?:boolean;onClick:()=>void}){return <button className="primary-action" disabled={disabled} onClick={onClick}>{children}<span>→</span></button>}

function UploadScreen({files,completion,onUpload,onRemove,onContinue}:{files:FileState[];completion:number;onUpload:(kind:string,event:ChangeEvent<HTMLInputElement>)=>void;onRemove:(kind:string)=>void;onContinue:()=>void}){return <div className="upload-screen"><header><span>El paso más importante</span><h1>Sube los antecedentes</h1><p>Con ellos validamos la propiedad y construimos un resultado confiable. Puedes fotografiar o adjuntar cada documento.</p></header><div className="upload-progress"><div><strong>{completion}% completado</strong><span>{files.length} de {documentTypes.length} antecedentes</span></div><div><i style={{width:`${completion}%`}}/></div><small>{completion===100?"Todo listo para continuar":"Tu avance queda guardado en este dispositivo"}</small></div><div className="upload-list">{documentTypes.map((doc,index)=>{const file=files.find(item=>item.kind===doc.kind);return <article className={file?"complete":""} key={doc.kind}><span className="upload-number">{file?"✓":index+1}</span><div><h2>{doc.title}</h2><p>{file?file.name:doc.help}</p>{file&&<small>{(file.size/1024/1024).toFixed(1)} MB · Documento recibido</small>}</div>{file?<button className="remove-file" onClick={()=>onRemove(doc.kind)}>Cambiar</button>:<label className="file-button">Subir archivo<input type="file" accept={doc.accept} onChange={event=>onUpload(doc.kind,event)}/></label>}</article>})}</div><div className="upload-security"><span>◉</span><p><b>Información protegida.</b> Tus antecedentes se vinculan únicamente a tu expediente privado.</p></div><Primary onClick={onContinue}>{completion===100?"Revisar mi solicitud":"Continuar y completar después"}</Primary></div>}

function Summary({answers,files,completion,folio,onEdit,onContinue}:{answers:Answers;files:FileState[];completion:number;folio:string;onEdit:(stage:number)=>void;onContinue:()=>void}){return <QuestionScreen eyebrow="Revisa antes de confirmar" title="Este es tu expediente" text={`Folio preliminar ${folio}`}><div className="summary-panel"><section><header><h2>Propiedad</h2><button onClick={()=>onEdit(2)}>Editar</button></header><dl><div><dt>Inmueble</dt><dd>{answers.propertyType}</dd></div><div><dt>Ubicación</dt><dd>{answers.address}, {answers.commune}</dd></div><div><dt>Superficie</dt><dd>{answers.area} m²</dd></div><div><dt>Finalidad</dt><dd>{answers.purpose}</dd></div></dl></section><section><header><h2>Servicio</h2><button onClick={()=>onEdit(0)}>Editar</button></header><dl><div><dt>Modalidad</dt><dd>{answers.service}</dd></div><div><dt>Entrega</dt><dd>{answers.service==="Express"?"Desde 24 h hábiles":"Según agenda coordinada"}</dd></div><div><dt>Antecedentes</dt><dd className={completion===100?"ok":"warn"}>{files.length}/3 · {completion}%</dd></div></dl></section><section><header><h2>Contacto</h2><button onClick={()=>onEdit(5)}>Editar</button></header><dl><div><dt>Solicitante</dt><dd>{answers.name}</dd></div><div><dt>Correo</dt><dd>{answers.email}</dd></div><div><dt>Teléfono</dt><dd>{answers.phone}</dd></div></dl></section></div>{completion<100&&<div className="soft-warning"><span>!</span><p><b>Aún hay antecedentes pendientes.</b> Puedes avanzar y completarlos después desde el seguimiento de tu expediente.</p></div>}<Primary onClick={onContinue}>Confirmar expediente</Primary></QuestionScreen>}

function Checkout({answers,completion,folio,onPay}:{answers:Answers;completion:number;folio:string;onPay:()=>void}){const express=answers.service==="Express";return <QuestionScreen eyebrow="Último paso" title={express?"Prueba la entrega Express":"Reserva tu revisión profesional"} text={express?"En esta validación no se realizará ningún cobro.":"Revisa los antecedentes y envía la solicitud."}><div className="checkout-card"><span>{answers.service.toUpperCase()}</span><div><h2>{express?"$39.990":"Desde 1,5 UF"}</h2><small>{express?"Precio comercial · simulación sin cobro":"Valor final confirmado antes de pagar"}</small></div><ul><li><b>✓</b> Expediente privado {folio}</li><li><b>✓</b> Antecedentes cargados: {completion}%</li><li><b>✓</b> Informe PDF demo descargable</li><li><b>✓</b> Análisis territorial TasaGo Geo</li></ul></div><div className="demo-payment-banner"><span>DEMO</span><div><strong>Simulación de Mercado Pago</strong><small>Generará inmediatamente un informe de ejemplo. No solicitará tarjeta ni realizará cargos.</small></div></div><button className="pay-button" onClick={onPay}>{express?"Simular pago y generar informe demo":"Enviar solicitud de visita"}<span>→</span></button><p className="demo-note">Al continuar pasarás al estado final y podrás descargar el PDF de demostración.</p></QuestionScreen>}

function Status({paid,answers,folio,completion,onNew}:{paid:boolean;answers:Answers;folio:string;completion:number;onNew:()=>void}){const express=answers.service==="Express";const delivered=paid&&express;const steps=express?["Pago demo confirmado","Antecedentes recibidos","Validación documental","Análisis TasaGo Geo","Informe PDF generado"]:["Solicitud recibida","Coordinación de visita","Inspección profesional","Análisis técnico","Informe PDF"];return <div className="status-screen"><div className="status-success"><span>✓</span><p>{delivered?"Simulación completada":paid?"Solicitud confirmada":"Expediente creado"}</p><h1>{delivered?"Tu Tasación Express demo está lista.":"Ya estamos trabajando por tu tranquilidad."}</h1><small>Folio {folio}</small></div><section className="status-card"><header><div><span>ESTADO ACTUAL</span><h2>{delivered?"Informe demo generado":express?"Validando antecedentes":"Coordinando visita"}</h2></div><b>{delivered?"Entregado":"En proceso"}</b></header><div className="status-timeline">{steps.map((step,index)=>{const done=delivered||index<2;const current=!delivered&&index===2;return <div className={done?"done":current?"current":""} key={step}><span>{done?"✓":index+1}</span><div><strong>{step}</strong><small>{done?"Completado":current?"En curso":"Siguiente etapa"}</small></div></div>})}</div></section>{!delivered&&completion<100&&<button className="missing-docs" onClick={()=>window.alert("En producción, este acceso abrirá la carga segura del expediente.")}><span>!</span><div><strong>Completa tus antecedentes</strong><small>Faltan antecedentes para acelerar la revisión</small></div><b>→</b></button>}<div className={`delivery-preview ${delivered?"available":""}`}><span>PDF</span><div><strong>{delivered?"Tasación Express demo":"Informe de tasación"}</strong><small>{delivered?"Incluye valor estimado, comparables y análisis territorial TasaGo Geo.":"Estará disponible aquí al finalizar el proceso"}</small></div>{delivered?<a href="/ejemplo-informe-express.pdf" download="TasaGo-Tasacion-Express-Demo.pdf">Descargar PDF</a>:<button disabled>Descargar</button>}</div>{delivered&&<a className="open-report" href="/ejemplo-informe-express.pdf" target="_blank">Abrir informe en el navegador ↗</a>}<p className="status-message">{delivered?"Este resultado es demostrativo y no corresponde a una tasación comercial definitiva.":<>Enviaremos cada avance a <b>{answers.email}</b>. No necesitas volver a completar tus datos.</>}</p><button className="new-request" onClick={onNew}>Volver al inicio</button></div>}
