"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Status="Solicitud"|"Antecedentes"|"En tasación"|"Entregado";
type Valuation={id:string;folio:string;clientName:string;clientEmail:string;clientPhone:string;propertyType:string;address:string;commune:string;usefulSurface:number;totalSurface:number;bedrooms:number;bathrooms:number;parking:number;purpose:string;plan:string;status:Status;fee:number;paymentStatus:string;estimatedValue:number;workflowStep:number;completionPercent:number;automationStatus:string;notes:string;createdAt:string;updatedAt:string};
type User={displayName:string;email:string};
const statusOrder:Status[]=["Solicitud","Antecedentes","En tasación","Entregado"];
const clp=(value:number)=>value?`$${Math.round(value).toLocaleString("es-CL")}`:"Por definir";

export default function Home(){
  const [valuations,setValuations]=useState<Valuation[]>([]),[user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true);
  const [showForm,setShowForm]=useState(false),[selected,setSelected]=useState<Valuation|null>(null),[notice,setNotice]=useState("");
  const notify=(message:string)=>{setNotice(message);window.setTimeout(()=>setNotice(""),4500)};
  const load=useCallback(async()=>{
    setLoading(true);
    const [valuationResponse,userResponse]=await Promise.all([fetch("/api/valuations"),fetch("/api/me")]);
    if(valuationResponse.ok)setValuations((await valuationResponse.json()).valuations);
    if(userResponse.ok)setUser((await userResponse.json()).user);
    setLoading(false);
  },[]);
  useEffect(()=>{void load()},[load]);
  const pipeline=useMemo(()=>statusOrder.map(status=>({status,count:valuations.filter(v=>v.status===status).length})),[valuations]);
  const active=valuations.filter(v=>v.status!=="Entregado").length, delivered=valuations.filter(v=>v.status==="Entregado").length;
  const managed=valuations.reduce((sum,v)=>sum+Number(v.estimatedValue||0),0);
  const pendingDocuments=valuations.filter(v=>(v.completionPercent||0)<100&&v.status!=="Entregado").length;
  const pendingPayment=valuations.filter(v=>v.paymentStatus==="Pendiente").length;
  const paid=valuations.filter(v=>v.paymentStatus==="Pagado"||v.paymentStatus==="Validación").length;
  const conversion=valuations.length?Math.round((paid/valuations.length)*100):0;

  async function createValuation(event:FormEvent<HTMLFormElement>){
    event.preventDefault();const form=event.currentTarget,data=Object.fromEntries(new FormData(form));
    const response=await fetch("/api/valuations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});
    const result=await response.json();if(!response.ok){notify(result.error||"No fue posible crear la solicitud");return}
    setShowForm(false);form.reset();notify(`Solicitud ${result.folio} creada correctamente.`);await load();
  }
  async function saveValuation(event:FormEvent<HTMLFormElement>){
    event.preventDefault();if(!selected)return;const data=Object.fromEntries(new FormData(event.currentTarget));
    const response=await fetch(`/api/valuations/${selected.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});
    const result=await response.json();if(!response.ok){notify(result.error||"No fue posible guardar");return}notify("Expediente actualizado.");setSelected(null);await load();
  }
  async function addComparable(event:FormEvent<HTMLFormElement>){
    event.preventDefault();if(!selected)return;const form=event.currentTarget,data=Object.fromEntries(new FormData(form));
    const response=await fetch(`/api/valuations/${selected.id}/comparables`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});
    const result=await response.json();if(!response.ok){notify(result.error||"No fue posible agregar el comparable");return}form.reset();notify("Comparable incorporado al expediente.");
  }
  async function startPayment(){
    if(!selected)return;const response=await fetch("/api/payments/create",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({valuationId:selected.id})});
    const result=await response.json();if(!response.ok){notify(result.error||"No fue posible iniciar el pago");return}window.location.href=result.checkoutUrl;
  }

  return <main className="panel-root app-shell">
    <aside className="sidebar"><div className="brand-card"><img src="/tasago-logo-final.png" alt="TasaGo Inteligencia Territorial" className="brand-logo"/></div>
      <nav className="nav-list" aria-label="Navegación principal"><a className="nav-item active" href="#resumen"><span>01</span>Resumen</a><a className="nav-item" href="#tasaciones"><span>02</span>Expedientes</a><a className="nav-item" href="#clientes"><span>03</span>CRM y clientes</a><a className="nav-item" href="#automatizacion"><span>04</span>Automatización</a><a className="nav-item" href="#mapa"><span>05</span>Territorio</a><a className="nav-item" href="#analitica"><span>06</span>Analítica</a></nav>
      <div className="sidebar-bottom"><div className="expert-card"><span className="expert-dot"/><div><strong>Datos sincronizados</strong><small>Región Metropolitana</small></div></div><button className="profile" type="button"><span className="avatar">{(user?.displayName||"JC").split(" ").map(p=>p[0]).join("").slice(0,2).toUpperCase()}</span><span><strong>{user?.displayName||"Usuario TasaGo"}</strong><small>{user?.email||"Sesión privada"}</small></span></button></div>
    </aside>
    <section className="workspace" id="resumen"><header className="topbar"><div><p className="eyebrow">Panel profesional · datos persistentes</p><h1>Buenas tardes, {user?.displayName?.split(" ")[0]||"Javier"}</h1><p className="subtitle">Control comercial y técnico de tus tasaciones.</p></div><div className="top-actions"><a className="icon-button signout" href="/signout-with-chatgpt?return_to=/">Cerrar sesión</a><button className="primary-button" onClick={()=>setShowForm(true)}>+ Nueva tasación</button></div></header>
      {notice&&<div className="toast" role="status">{notice}</div>}
      <section className="metrics"><article className="metric-card featured"><span className="metric-label">Tasaciones activas</span><strong>{active}</strong><small>Expedientes que requieren gestión</small></article><article className="metric-card"><span className="metric-label">Conversión a pago</span><strong>{conversion}%</strong><small>{paid} expedientes activados</small></article><article className="metric-card"><span className="metric-label">Antecedentes pendientes</span><strong>{pendingDocuments}</strong><small>Clientes que requieren seguimiento</small></article><article className="metric-card"><span className="metric-label">Valor gestionado</span><strong>{managed?clp(managed):"$0"}</strong><small>{delivered} informes entregados</small></article></section>
      <section className="content-grid"><article className="panel pipeline-panel"><div className="panel-heading"><div><p className="eyebrow">Flujo de trabajo</p><h2>Pipeline de tasaciones</h2></div><button onClick={()=>document.querySelector("#tasaciones")?.scrollIntoView()}>Ver todas</button></div><div className="pipeline">{pipeline.map((item,index)=><div className="pipeline-step" key={item.status}><span className={`step-marker step-${index}`}>{item.count}</span><div><strong>{item.status}</strong><small>{item.count===1?"expediente":"expedientes"}</small></div>{index<3&&<span className="connector"/>}</div>)}</div></article>
        <article className="panel territory-panel" id="mapa"><div className="territory-copy"><p className="eyebrow green">TasaGo Geo</p><h2>Inteligencia territorial</h2><p>Los comparables ingresados alimentan el análisis de cada expediente.</p><div className="geo-stat"><strong>{valuations.length}</strong><span>expedientes<br/>georreferenciables</span></div></div><div className="map-visual"><div className="map-grid"/><span className="map-pin pin-one">LC</span><span className="map-pin pin-two">PR</span><span className="map-pin pin-three">ÑU</span><span className="map-pin pin-four">ST</span><div className="map-caption"><span/>RM · base preparada para mapa conectado</div></div></article></section>
      <section className="panel table-panel" id="tasaciones"><div className="panel-heading"><div><p className="eyebrow">Gestión operativa</p><h2>Expedientes y CRM</h2></div><div className="table-actions"><span className="sync-state">{loading?"Sincronizando…":"Base actualizada"}</span><button onClick={()=>void load()}>Actualizar</button></div></div><div className="table-wrap"><table><thead><tr><th>Folio</th><th>Cliente y propiedad</th><th>Servicio</th><th>Antecedentes</th><th>Estado</th><th>Pago</th><th>Valor</th><th></th></tr></thead><tbody>{!loading&&!valuations.length&&<tr><td colSpan={8} className="empty-state">Aún no hay tasaciones. Crea el primer expediente para comenzar.</td></tr>}{valuations.map(v=><tr key={v.id}><td><strong>{v.folio}</strong></td><td><strong>{v.clientName}</strong><small>{v.clientEmail||v.clientPhone||"Contacto pendiente"}</small></td><td><strong>{v.plan||"Interno"}</strong><small>{v.propertyType} · {v.usefulSurface} m²</small></td><td><strong>{v.completionPercent||0}%</strong><small>Paso {v.workflowStep||1} de 7</small></td><td><span className={`status status-${v.status.replaceAll(" ","-").toLowerCase()}`}>{v.status}</span></td><td><span className={`payment payment-${v.paymentStatus.toLowerCase()}`}>{v.paymentStatus}</span></td><td>{clp(v.estimatedValue)}</td><td><button className="row-action" onClick={()=>setSelected(v)}>Abrir</button></td></tr>)}</tbody></table></div></section>
      <section className="operations-grid" id="clientes"><article className="panel action-panel"><div className="panel-heading"><div><p className="eyebrow">CRM comercial</p><h2>Prioridades de contacto</h2></div></div><div className="action-list"><div><span className="action-dot amber"/><p><b>{pendingDocuments} expedientes con faltantes</b><small>Enviar recordatorio de antecedentes</small></p></div><div><span className="action-dot blue"/><p><b>{pendingPayment} pagos pendientes</b><small>Retomar solicitudes listas para activar</small></p></div><div><span className="action-dot green"/><p><b>{delivered} clientes con informe</b><small>Solicitar evaluación sólo con autorización</small></p></div></div></article><article className="panel action-panel" id="automatizacion"><div className="panel-heading"><div><p className="eyebrow green">Motor operativo</p><h2>Automatización e IA</h2></div></div><div className="automation-summary"><strong>{valuations.filter(v=>v.automationStatus==="Completado").length}</strong><span>procesos completados</span><p>Validación → OCR/IA → ficha técnica → comparables → valoración → PDF</p><small>Las excepciones quedan listas para revisión humana.</small></div></article><article className="panel action-panel" id="analitica"><div className="panel-heading"><div><p className="eyebrow">Analítica</p><h2>Salud del negocio</h2></div></div><div className="analytics-bars"><label><span>Conversión a pago</span><b>{conversion}%</b><i><em style={{width:`${conversion}%`}}/></i></label><label><span>Documentación completa</span><b>{valuations.length?Math.round((valuations.filter(v=>(v.completionPercent||0)>=100).length/valuations.length)*100):0}%</b><i><em style={{width:`${valuations.length?Math.round((valuations.filter(v=>(v.completionPercent||0)>=100).length/valuations.length)*100):0}%`}}/></i></label></div></article></section>
    </section>
    {showForm&&<div className="modal-backdrop" onMouseDown={()=>setShowForm(false)}><section className="modal" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><p className="eyebrow">Nuevo expediente</p><h2>Ficha inicial de tasación</h2></div><button onClick={()=>setShowForm(false)}>×</button></div><form onSubmit={createValuation}>
      <div className="form-section-title">Cliente</div><label>Nombre completo o razón social<input name="clientName" required autoFocus/></label><div className="form-row"><label>Correo<input name="clientEmail" type="email"/></label><label>Teléfono<input name="clientPhone"/></label></div>
      <div className="form-section-title">Inmueble</div><div className="form-row"><label>Tipo<select name="propertyType" defaultValue="Departamento"><option>Departamento</option><option>Casa</option><option>Terreno</option><option>Local comercial</option><option>Oficina</option><option>Bodega</option></select></label><label>Comuna<select name="commune" defaultValue=""><option value="" disabled>Seleccionar</option><option>Las Condes</option><option>Providencia</option><option>Ñuñoa</option><option>Santiago</option><option>Vitacura</option><option>La Reina</option><option>Colina</option><option>Otra comuna RM</option></select></label></div><label>Dirección<input name="address" required/></label><div className="form-three"><label>Sup. útil<input name="usefulSurface" type="number" min="1" required/></label><label>Sup. total<input name="totalSurface" type="number" min="0"/></label><label>Finalidad<select name="purpose"><option>Comercial</option><option>Garantía bancaria</option><option>Judicial</option><option>Tributaria</option><option>Seguro</option></select></label></div><div className="form-three"><label>Dormitorios<input name="bedrooms" type="number" min="0"/></label><label>Baños<input name="bathrooms" type="number" min="0"/></label><label>Estacionamientos<input name="parking" type="number" min="0"/></label></div><label>Observaciones<textarea name="notes" rows={3}/></label><div className="modal-actions"><button className="secondary-button" type="button" onClick={()=>setShowForm(false)}>Cancelar</button><button className="primary-button" type="submit">Crear expediente</button></div></form></section></div>}
    {selected&&<div className="modal-backdrop" onMouseDown={()=>setSelected(null)}><section className="modal detail-modal" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><p className="eyebrow">{selected.folio}</p><h2>{selected.clientName}</h2><p className="detail-address">{selected.address}, {selected.commune}</p></div><button onClick={()=>setSelected(null)}>×</button></div>
      <form onSubmit={saveValuation}><div className="detail-grid"><label>Estado<select name="status" defaultValue={selected.status}>{statusOrder.map(s=><option key={s}>{s}</option>)}</select></label><label>Honorarios CLP<input name="fee" type="number" min="0" defaultValue={selected.fee}/></label><label>Valor comercial CLP<input name="estimatedValue" type="number" min="0" defaultValue={selected.estimatedValue}/></label><label>Estado de pago<select name="paymentStatus" defaultValue={selected.paymentStatus}><option>Pendiente</option><option>Pagado</option><option>Rechazado</option><option>Cancelado</option></select></label></div><label>Observaciones técnicas<textarea name="notes" rows={4} defaultValue={selected.notes}/></label><div className="record-actions"><button className="secondary-button" type="button" onClick={()=>void startPayment()}>Cobrar con Mercado Pago</button><a className="secondary-button report-link" href={`/api/valuations/${selected.id}/report`}>Descargar informe PDF</a><button className="primary-button" type="submit">Guardar cambios</button></div></form>
      <div className="comparable-block" id="comparables"><div><p className="eyebrow green">Análisis de mercado</p><h3>Agregar comparable</h3></div><form className="comparable-form" onSubmit={addComparable}><input name="address" required placeholder="Dirección del comparable"/><input name="price" required type="number" min="1" placeholder="Precio CLP"/><input name="surface" required type="number" min="1" placeholder="Superficie m²"/><input name="source" placeholder="Fuente"/><button className="primary-button" type="submit">Agregar</button></form></div>
    </section></div>}
  </main>;
}
